// <auto-generated />
namespace Aircraft.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class v1_base : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1_base));
        
        string IMigrationMetadata.Id
        {
            get { return "201911190228147_v1_base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
